name: Build CI

on:
  push:
    tags:
      - rc-0.0.[0-9]+

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.16.0'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci
      - name: Check lint
        run: npm run lint
      - name: Check typescript
        run: npm run ts
      - name: Build
        run: npm run build

      - name: Create Docker
        uses: ./.github/scripts/docker
      - name: Publish info
        uses: ./.github/scripts/publish-info
        with:
          oauth: ${{secrets.YANDEX_OAUTH}}
          orgid: ${{secrets.ORG_ID}}

